- 1.1.10
- _NAME: Multi Device Silent Mouse M585/M590
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, dpi, speed-change, backlight, backlight-timed, fn-swap, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys,
    m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4096
  _modelId: B01B406B0000
  _serial: 255C4039
  _unitId: A3E6E9D8
  _wpid: 406B
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 91: 0, 93: 0}
  lowres-scroll-mode: false
  persistent-remappable-keys: null
  pointer_speed: 256
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 91: 91, 93: 93}
